{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[1m])) * 60",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum by(method) (rate(requests_total{source=\"jwt-pizza-service\"}[1m])) * 60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Auth Attempts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(auth_attempts_total{result=\"success\", source=\"jwt-pizza-service\"}[1m])) * 60",
     "legendFormat": "Success Attempts/min"
    },
    {
     "expr": "sum(rate(auth_attempts_total{result=\"failed\", source=\"jwt-pizza-service\"}[1m])) * 60",
     "legendFormat": "Failure Attempts/min"
    }
   ]
  },
  {
   "title": "Pizzas Sold/Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Pizzas Sold/min"
    },
    {
     "expr": "rate(order_failures_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Failed Creation/min"
    }
   ]
  },
  {
   "title": "Revenue/Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "rate(revenue_USD_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Revenue/min"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cpu_percent{source=\"jwt-pizza-service\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "latency_avg_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pizza_latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  }
 ]
}